name: 'BrightSign Manual Build Process'
on: 
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        type: choice
        options:
        - test
        - release

      instance_type:
        description: 'EC2 Instance Type'
        type: choice
        options:
        - c5.large
        - c5.xlarge
        - c5.2xlarge
        - c5.4xlarge

      stop_instance_after_use:
        description: 'Stop EC2 instance after use'
        type: boolean
        default: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  call-build-and-test:
    uses: ./.github/workflows/bs_electron_ci_ec2.yml
    secrets: inherit
    with:
      build_type: ${{ inputs.build_type }}
      instance_type: ${{ inputs.instance_type }}
      stop_instance_after_use: ${{ inputs.stop_instance_after_use }}
      instance_name_postfix: manual--${{ github.actor }}
      aws_arn_role: arn:aws:iam::307112297008:role/github-actions-electron-private-repo
      aws_region: us-east-1
