name: 'BrightSign Release Processes'
on: 
  create:
  delete:
    tags:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  create-release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    uses: ./.github/workflows/bs_electron_ci_ec2.yml
    secrets: inherit
    with:
      build_type: release
      aws_arn_role: arn:aws:iam::307112297008:role/github-actions-electron-private-repo
      aws_region: us-east-1

  delete-release:
    if: github.event_name == 'delete' && github.event.ref_type == 'tag' # startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
        - name: Info
          run: echo "TODO.. Delete release with Tag" ${{ github.event.ref }}

  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: |
  #         echo "$GITHUB_CONTEXT"    
